# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Integracao Continua Exemplo FatecZL

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 - Para compilar e fazer testes
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Gerando Arquivo JAR
      run: mvn -B package --file pom.xml
      
    - name: Listando conteudo gerado
      run: ls -laR
      
    - name: Upload para VM do Isidro
      uses: appleboy/scp-action@master
      with:
         host: cloud.professorisidro.com.br
         port: 22
         username: root
         password: ${{ secrets.PASSWORD }}
         source: "./target/*.jar"
         target: "/root"
    
    - name: Executando Script de Deploy na VM Remota
      uses: appleboy/ssh-action@master
      with: 
         host: cloud.professorisidro.com.br
         port: 22
         username: root
         password: ${{ secrets.PASSWORD }}
         target: /root/deployfateczl.sh
            
       
